Date:Sun Apr 22 07:10:14 PM EDT 2012
Input command file generated by LEDA

#VERILOGCompiler	/package/eda/synopsys/leda-E-2010.12/amd64/bin/ve -M +no_lvs_env  -c -z -p2 -i -k95e -log /home/ecegrid/a/mg56/ece337/project_new/leda-logs/compiler.log -full_log -snote +max_case+8 +max_casexz+8 -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#VHDLCompiler	/package/eda/synopsys/leda-E-2010.12/amd64/bin/v -M +no_lvs_env  -c -z -i -k93e -log /home/ecegrid/a/mg56/ece337/project_new/leda-logs/compiler.log -full_log -snote -config_file /home/ecegrid/a/ece337/Class0.5u/.leda_config.tcl
#HOMELESS	LEDA_WORK
#Makefile-Name	LEDA_Makefile
#Makelibs-Name	LEDA_Makelibs
#Project-Name	/home/ecegrid/a/mg56/ece337/project_new/leda.pro

#VHDLSuffixes
#End

#VHDLSuffixes
#End

#VERILOGSuffixes
#End
#Mappings
#End
#Files LEDA_WORK
#End

#VERILOGSuffixes
#End

#VHDLSuffixes
vhd -
vhdl -
#End
#Mappings
#End
#Files LEDA_WORK
   /home/ecegrid/a/mg56/ece337/project_new/source/FifoRam.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/FifoRead.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/FifoTop.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/FifoWrite.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/NRZIdecode.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/SEE_det.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/SpiClkDivide.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/SpiXmitSR.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/computerInterceptor.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/controller.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/decoder.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/interceptor.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/lockingDetector.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/sd_control.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/shift_greg.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/sniffer_top.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/timer.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/tristate.vhd
   /home/ecegrid/a/mg56/ece337/project_new/source/usbInterceptor.vhd
#End
#Resources
   IEEE $LEDA_PATH/amd64/resources/resource_93/IEEE 
   SNPS_EXT $LEDA_PATH/amd64/resources/resource_93/SNPS_EXT 
   STD $LEDA_PATH/amd64/resources/resource_93/STD 
   SYNOPSYS $LEDA_PATH/amd64/resources/resource_93/SYNOPSYS 
#End
