-- VHDL Entity my_project1_lib.fifo_test.symbol
--
-- Created:
--          by - mg147.bin (srge00.ecn.purdue.edu)
--          at - 18:18:44 04/10/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY fifo_test IS
  generic(
    gregLength : integer := 16;
      gregWidth  : integer := 8;
      srWidth : integer :=8;
      addrSize  : integer := 4      -- 2^addrSize = gregLength
    
  );
   PORT( 
      clk       : IN     std_logic;
      rEnable   : IN     std_logic;
      resetN    : IN     std_logic;
      shiftCtrl : IN     std_logic;
      tsrEnable : IN     std_logic;
      wData     : IN     std_logic_vector (gregWidth-1 DOWNTO 0);
      wEnable   : IN     std_logic;
      tsrLoad   : IN    std_logic;
      dataOut   : OUT    std_logic;
      fifoEmpty : OUT    std_logic;
      fifoFull  : OUT    std_logic
   );

-- Declarations

END fifo_test ;

--
-- VHDL Architecture my_project1_lib.fifo_test.struct
--
-- Created:
--          by - mg147.bin (srge00.ecn.purdue.edu)
--          at - 18:18:44 04/10/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ARCHITECTURE struct OF fifo_test IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL tsrData : std_logic_vector(srWidth-1 DOWNTO 0);


   -- Component Declarations
   COMPONENT FifoTop
   GENERIC (
      gregLength : integer := 16;
      gregWidth  : integer := 8;
      addrSize  : integer := 4      -- 2^addrSize = gregLength
   );
   PORT (
      clk       : IN     std_logic;
      rEnable   : IN     std_logic;
      resetN    : IN     std_logic;
      wData     : IN     std_logic_vector (gregWidth-1 DOWNTO 0);
      wEnable   : IN     std_logic;
      fifoEmpty : OUT    std_logic;
      fifoFull  : OUT    std_logic;
      rData     : OUT    std_logic_vector (gregWidth-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT SpiXmitSR
   GENERIC (
      srWidth : integer := 8
   );
   PORT (
      clk       : IN     std_logic;
      resetN    : IN     std_logic;
      shiftCtrl : IN     std_logic;
      tsrData   : IN     std_logic_vector (srWidth-1 DOWNTO 0);
      tsrEnable : IN     std_logic;
      tsrLoad   : IN     std_logic;
      dataOut   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : FifoTop
      GENERIC MAP (
         gregLength => 16,
         gregWidth  => 8,
         addrSize  => 4         -- 2^addrSize = gregLength
      )
      PORT MAP (
         clk       => clk,
         rEnable   => rEnable,
         resetN    => resetN,
         wData     => wData,
         wEnable   => wEnable,
         fifoEmpty => fifoEmpty,
         fifoFull  => fifoFull,
         rData     => tsrData
      );
   U_1 : SpiXmitSR
      GENERIC MAP (
         srWidth => 8
      )
      PORT MAP (
         clk       => clk,
         resetN    => resetN,
         tsrEnable => tsrEnable,
         shiftCtrl => shiftCtrl,
         tsrLoad   => rEnable,
         tsrData   => tsrData,
         dataOut   => dataOut
      );

END struct;
